import TopNav from "@ui/layout/topnav";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
        [background:radial-gradient(ellipse_100%_40%_at_top_center,_#291156,_#291156_60%,_transparent_60%),_#17151e] 
        bg-no-repeat 
        [background-size:100%_50%]`}
      >
        <TopNav />
        {children}
      </body>
    </html>
  );
}
